name: CD
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build_site:
    name: Build Site
    # prevents this action from running on forks
    if: github.repository == 'binhtran432k/MiniAssetManagement'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
      - name: Install wasm
        run:  dotnet workload install wasm-tools
      - name: Publish
        run: dotnet publish MiniAssetManagement.csproj -c Release
      - name: Hack Github Pages
        working-directory: ./bin/Release/net8.0/publish/wwwroot
        run: cp index.html 404.html
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./bin/Release/net8.0/publish/wwwroot
  deploy:
    name: Deploy Github Pages
    runs-on: ubuntu-latest
    needs: build_site
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4